### ISSUE TITLE
Should we give gl-modules a new name?

### ISSUE THREAD

**Issue by hughsk** [stackgl/gl-modules.github.io#6]
For the sake of :sparkles:branding:sparkles: – even though it's the core focus of the project, modularity is still something a niche concern outside the node community. If we could get an nice name for the project to go with the new website I think it'd make a ton of difference to getting other people on board.

What do you guys think?

**Comment by mikolalysenko** [comment]
I'm open to the idea, any thoughts?  @chrisdickinson @maxogden @tmpvar 

Also would be great to get a logo/character illustration for the project. (Maybe @substack could help?)

**Comment by mikolalysenko** [comment]
On a related note, we should probably stake out an IRC channel somewhere. (and I need to somehow reset my freenode password...)

**Comment by chrisdickinson** [comment]
If it's cool I'd love to take a stab at drawing up a logo!

**Comment by hughsk** [comment]
@chrisdickinson yeah go for it! Hexagon-sticker-friendly? :)

**Comment by hughsk** [comment]
@timoxley and I had a look around, tricky though!
- polyhydra / polytope
- propane / halogen (ties in mercury?)
- apex / tessellate
- alloy
- spectra

**Comment by mikolalysenko** [comment]
@hughsk  proposed _stackgl_, which I really like.  Any thoughts?

**Comment by tmpvar** [comment]
stackgl is good :thumbsup:

**Comment by mikolalysenko** [comment]
Ok, I just registered stack.gl

Now I need to figure out how @maxogden set up the DNS redirection for modules.gl in the first place....

**Comment by tmpvar** [comment]
@mikolalysenko https://github.com/gl-modules/gl-modules.github.io/blob/master/CNAME

**Comment by timoxley** [comment]
:+1: stackgl

**Comment by mikolalysenko** [comment]
@chrisdickinson can you weigh in before I pull the trigger on this one?

**Comment by chrisdickinson** [comment]
Ah -- sorry for the delay. One thing to keep in mind in changing the name is that we'll have to go through and change all of the git urls on each package + bump patch version. Not insurmountable! But want to make sure we remember to do that :)

I'm :+1: on stackgl, though!

**Comment by hughsk** [comment]
Cool! We've got the `#stackgl` IRC channel on freenode too – I've also just pushed [a WIP](https://github.com/gl-modules/gl-modules.github.io/tree/wip) for the site, if you guys wanna check it out :)

**Comment by hughsk** [comment]
WIP site is now published here for now: http://hughsk.io/stackgl-site/

@mikolalysenko it seems to be having issues on Firefox, could it be something to do with floating point textures by any chance?

**Comment by timoxley** [comment]
@hughsk oooooooooo looks pretty

**Comment by timoxley** [comment]
+1 milk cubes

**Comment by hughsk** [comment]
@timoxley haha :D

**Comment by mikolalysenko** [comment]
@hughsk  that looks awesome!  I will work on putting together some text for the header/mission statement, that everyone can pick apart/iterate on.

**Comment by hughsk** [comment]
@mikolalysenko thanks! Sounds good :)

**Comment by mikolalysenko** [comment]
Done!  Now to go through and update everything's package.json
